apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "leyline-assignment.fullname" . }}
  labels:
    {{- include "leyline-assignment.labels" . | nindent 4 }}
data:
  {{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}