apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leyline-assignment.fullname" . }}
  labels:
    {{- include "leyline-assignment.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.secretEnv.MYSQL_PASSWORD | quote }}
