name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Run tests with pytest
      run: pytest --cov=./ --cov-report=html
    - name: Upload coverage to artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: htmlcov


  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run linter
      run: flake8 ./app/

  build:
    needs: [test, lint]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: sudo docker build -t leyline-assignment:${{ github.sha }} .
    - name: Save Docker image
      run: sudo docker save leyline-assignment:${{ github.sha }} > leyline-assignment.tar
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: leyline-assignment.tar
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    # - name: Push Docker image
    #   run: |
    #     docker tag leyline-assignment:${{ github.sha }} your-docker-registry/leyline-assignment:${{ github.sha }}
    #     docker push your-docker-registry/leyline-assignment:${{ github.sha }}

  package:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0
    - name: Package Helm chart
      run: |
        helm package ./leyline-assignment --version ${{ github.sha }}
        helm repo index .
    - name: Upload Helm chart
      uses: actions/upload-artifact@v2
      with:
        name: helm-chart
        path: leyline-assignment-${{ github.sha }}.tgz