name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Run tests with pytest
      run: pytest --cov=./ --cov-report=html
    - name: Upload coverage to artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: htmlcov


  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run linter
      run: flake8 ./app/

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: leyline-assignment:${{ github.sha }}
        outputs: type=docker,dest=/tmp/leyline-assignment.tar
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: /tmp/leyline-assignment.tar
    #  commented out as i don't want to push the docker image into registry
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    # - name: Push Docker image
    #   run: |
    #     docker tag leyline-assignment:${{ github.sha }} your-docker-registry/leyline-assignment:${{ github.sha }}
    #     docker push your-docker-registry/leyline-assignment:${{ github.sha }}

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.0
    - name: Package Helm chart
      run: |
        helm package ./leyline-assignment-chart
        helm repo index .
    - name: Upload Helm chart
      uses: actions/upload-artifact@v2
      with:
        name: helm-chart
        path: leyline-assignment-0.1.0.tgz